# Languages
# Create a section for each of your site's languages.
# Documentation: https://docs.hugoblox.com/reference/language/

# Default language
zh:
  languageCode: zh-Hans  # 设置为简体中文
  contentDir: content/zh  # 设置中文内容文件夹为 content/zh
  title: 中文网站标题  # 网站标题
  params:
    description: 中文网站描述  # 网站描述
  menu:
    main:
      - name: 传
        url: '#about'
        weight: 1  # 菜单顺序

# Uncomment the lines below to configure your website in a second language.
# en:
#   languageCode: en-us
#   contentDir: content/en
